<?php
/**
 * Copyright © 2016 bss. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \bss\customordernumber\Block\System\Config\Collect */ ?>
<?php if($block->isShipmentEnable($block->getRequest()->getParam('store', 0))) { ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var shipmentSpan = jQuery('#shipment_span');

        jQuery('#resetnow_shipment').click(function () {
            var params = {storeId: <?php echo "'".$this->getRequest()->getParam('store', 0)."'"; ?>};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    shipmentSpan.find('.success').hide();
                    shipmentSpan.find('.processing').show();
                    jQuery('#shipment_message').text('');
                },
                onSuccess: function(response) {
                    shipmentSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        shipmentSpan.find('.success').show();
                    }
                    jQuery('#shipment_message').text(resultText);
                }
            });
        });

    });
</script>
<?php } ?>
<?php echo $block->getButtonHtml() ?>
<span id="shipment_span">
    <img class="processing" hidden="hidden" alt="" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="success" hidden="hidden" alt="" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="shipment_message"></span>
</span>