<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *
 * MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_CustomOrderNumber
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php if($block->isOrderEnable($block->getRequest()->getParam('store', 0))) { ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var orderSpan = jQuery('#order_span');

        jQuery('#resetnow_order').click(function () {
            var params = {storeId: <?php echo "'".$this->getRequest()->getParam('store', 0)."'"; ?>};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    orderSpan.find('.success').hide();
                    orderSpan.find('.processing').show();
                    jQuery('#order_message').text('');
                },
                onSuccess: function(response) {
                    orderSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        orderSpan.find('.success').show();
                    }
                    jQuery('#order_message').text(resultText);
                }
            });
        });

    });
</script>
<?php } ?>
<?php echo $block->getButtonHtml() ?>
<span id="order_span">
    <img class="processing" hidden="hidden" alt="" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="success" hidden="hidden" alt="" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="order_message"></span>
</span>